name: linters
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  js-linter:
    name: Javascript linter (standard)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Init yarn
        run: yarn install
      - name: Run Standard
        run: yarn standard html/index.js
      - uses: crate-ci/typos@master
  css-linter:
    name: CSS linter (stylelint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Init yarn
        run: yarn install
      - name: Run stylelint
        run: yarn stylelint html/*.css
  html-linter:
    name: HTML linter (html5validator) 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: html/
          extra: --ignore inline
